USE cloudcart;

ALTER TABLE orders ADD COLUMN customer_name VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN phone VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN email VARCHAR(254) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN address_line1 VARCHAR(180) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN address_line2 VARCHAR(180) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN city VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN district VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN state VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN pincode VARCHAR(6) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN latitude DECIMAL(10,7) NULL;
ALTER TABLE orders ADD COLUMN longitude DECIMAL(10,7) NULL;
ALTER TABLE orders ADD COLUMN payment_method VARCHAR(40) NOT NULL DEFAULT 'Pay on Delivery';
ALTER TABLE orders ADD COLUMN payment_status VARCHAR(30) NOT NULL DEFAULT 'Pending';
ALTER TABLE orders ADD COLUMN expected_delivery_at TIMESTAMP NULL;
ALTER TABLE orders ADD COLUMN tracking_token_hash CHAR(64) NULL;

UPDATE orders
SET expected_delivery_at = DATE_ADD(created_at, INTERVAL 24 HOUR)
WHERE expected_delivery_at IS NULL;
