import { NavLink } from 'react-router-dom'

const evidenceRecords = [
  {
    id: 'EV-001',
    domain: 'INFRASTRUCTURE',
    title: 'Terraform Validation',
    status: 'PENDING',
    description:
      'Infrastructure configuration will be validated with formatting, initialization, validation, planning, and security checks.',
    command: 'terraform fmt / validate / plan',
  },
  {
    id: 'EV-002',
    domain: 'CONTAINERS',
    title: 'Image Security Scan',
    status: 'PENDING',
    description:
      'Container images will be scanned for known vulnerabilities before they become deployment artifacts.',
    command: 'trivy image <image>',
  },
  {
    id: 'EV-003',
    domain: 'KUBERNETES',
    title: 'Workload Health',
    status: 'PENDING',
    description:
      'Application workloads will be validated using deployment status, pod health, probes, and service connectivity.',
    command: 'kubectl get pods / describe',
  },
  {
    id: 'EV-004',
    domain: 'SECURITY',
    title: 'Detection Workflow',
    status: 'PENDING',
    description:
      'A controlled security event will be traced from detection through notification and response.',
    command: 'Finding → EventBridge → Response',
  },
  {
    id: 'EV-005',
    domain: 'RESILIENCE',
    title: 'Deployment Rollback',
    status: 'PENDING',
    description:
      'A controlled unhealthy release scenario will be used to validate rollback and service recovery.',
    command: 'Deploy → Detect → Rollback',
  },
  {
    id: 'EV-006',
    domain: 'OBSERVABILITY',
    title: 'Telemetry Correlation',
    status: 'PENDING',
    description:
      'Metrics, logs, traces, and audit events will be correlated during troubleshooting scenarios.',
    command: 'Metric → Log → Trace → Evidence',
  },
]

const validationStages = [
  ['01', 'Build', 'Create the change or workload.'],
  ['02', 'Execute', 'Run the controlled test scenario.'],
  ['03', 'Observe', 'Capture metrics, logs, and system behavior.'],
  ['04', 'Verify', 'Compare the result with the expected outcome.'],
  ['05', 'Record', 'Preserve the actual evidence.'],
]

function Evidence() {
  return (
    <div className="evidence-page">
      {/* HERO */}
      <section className="section evidence-hero">
        <div className="container">
          <div className="evidence-header">
            <div>
              <div className="section-kicker">Evidence Center</div>

              <h1 className="evidence-title">
                Don't just say
                <br />
                <span>prove it.</span>
              </h1>

              <p className="section-description evidence-description">
                CloudCart is designed so infrastructure, security, deployment,
                observability, and resilience claims are backed by actual
                validation evidence.
              </p>
            </div>

            <div className="evidence-file">
              <div className="evidence-file-top">
                <span>PROJECT RECORD</span>
                <span>CONTROLLED</span>
              </div>

              <div className="evidence-file-id">
                CLOUDCART / EVIDENCE
              </div>

              <div className="evidence-file-meta">
                <div>
                  <small>Environment</small>
                  <strong>Lab / Portfolio</strong>
                </div>

                <div>
                  <small>Evidence model</small>
                  <strong>Actual results</strong>
                </div>

                <div>
                  <small>Test policy</small>
                  <strong>Controlled</strong>
                </div>

                <div>
                  <small>Fake results</small>
                  <strong>Never</strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* EVIDENCE PHILOSOPHY */}
      <section className="section">
        <div className="container">
          <div className="evidence-manifest">
            <div className="evidence-manifest-label">
              EVIDENCE PRINCIPLE
            </div>

            <div className="evidence-manifest-main">
              <h2>
                Configuration is not proof.
                <br />
                Successful validation is proof.
              </h2>

              <p>
                A Terraform file, Kubernetes manifest, security policy, or
                dashboard only describes what was intended. The evidence layer
                records what actually happened when the platform was tested.
              </p>
            </div>

            <div className="evidence-principles">
              <div>
                <span>01</span>
                <strong>Real</strong>
                <small>Generated by the actual environment.</small>
              </div>

              <div>
                <span>02</span>
                <strong>Traceable</strong>
                <small>Connected to a test or implementation.</small>
              </div>

              <div>
                <span>03</span>
                <strong>Repeatable</strong>
                <small>Another engineer can reproduce the test.</small>
              </div>

              <div>
                <span>04</span>
                <strong>Honest</strong>
                <small>Unverified results stay unverified.</small>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* RECORDS */}
      <section className="section" id="records">
        <div className="container">
          <div className="evidence-section-heading">
            <div>
              <div className="section-kicker">Evidence Register</div>

              <h2 className="section-title">
                Validation records
              </h2>
            </div>

            <p className="section-description">
              These records define what CloudCart intends to prove. They will
              be updated with real output after each test is executed.
            </p>
          </div>

          <div className="evidence-register">
            <div className="evidence-register-head">
              <span>RECORD</span>
              <span>DOMAIN</span>
              <span>VALIDATION</span>
              <span>STATE</span>
            </div>

            {evidenceRecords.map((record) => (
              <article className="evidence-record" key={record.id}>
                <div className="evidence-record-id">
                  {record.id}
                </div>

                <div className="evidence-record-domain">
                  {record.domain}
                </div>

                <div className="evidence-record-main">
                  <h3>{record.title}</h3>

                  <p>{record.description}</p>

                  <code>{record.command}</code>
                </div>

                <div className="evidence-record-status">
                  <span>{record.status}</span>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* VALIDATION PROCESS */}
      <section className="section">
        <div className="container">
          <div className="evidence-section-heading">
            <div>
              <div className="section-kicker">Validation Method</div>

              <h2 className="section-title">
                Every test follows a controlled sequence.
              </h2>
            </div>
          </div>

          <div className="validation-timeline">
            {validationStages.map(([number, title, description], index) => (
              <div className="validation-step" key={number}>
                <div className="validation-marker">
                  {number}
                </div>

                <div className="validation-content">
                  <strong>{title}</strong>
                  <p>{description}</p>
                </div>

                {index < validationStages.length - 1 && (
                  <div className="validation-line" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PROOF CATEGORIES */}
      <section className="section">
        <div className="container">
          <div className="evidence-section-heading">
            <div>
              <div className="section-kicker">Proof Categories</div>

              <h2 className="section-title">
                What the evidence will contain.
              </h2>
            </div>
          </div>

          <div className="proof-grid">
            <article className="proof-folder">
              <div className="proof-folder-top">
                <span>01</span>
                <span>INFRA</span>
              </div>

              <h3>Infrastructure</h3>

              <p>
                Terraform output, resource state, network validation,
                architecture verification, and infrastructure test results.
              </p>

              <div className="proof-file">
                <span>terraform-plan.txt</span>
                <span>TEXT</span>
              </div>

              <div className="proof-file">
                <span>terraform-validate.txt</span>
                <span>TEXT</span>
              </div>

              <div className="proof-file">
                <span>architecture.png</span>
                <span>IMAGE</span>
              </div>
            </article>

            <article className="proof-folder">
              <div className="proof-folder-top">
                <span>02</span>
                <span>SECURITY</span>
              </div>

              <h3>Security</h3>

              <p>
                Security findings, WAF tests, access-control validation,
                response events, and incident-response records.
              </p>

              <div className="proof-file">
                <span>security-event.json</span>
                <span>JSON</span>
              </div>

              <div className="proof-file">
                <span>waf-test.txt</span>
                <span>TEXT</span>
              </div>

              <div className="proof-file">
                <span>response-timeline.md</span>
                <span>MD</span>
              </div>
            </article>

            <article className="proof-folder">
              <div className="proof-folder-top">
                <span>03</span>
                <span>DELIVERY</span>
              </div>

              <h3>CI/CD</h3>

              <p>
                Workflow runs, security scan results, container metadata,
                deployment history, and rollback evidence.
              </p>

              <div className="proof-file">
                <span>pipeline-run.md</span>
                <span>MD</span>
              </div>

              <div className="proof-file">
                <span>trivy-report.txt</span>
                <span>TEXT</span>
              </div>

              <div className="proof-file">
                <span>deployment-history.md</span>
                <span>MD</span>
              </div>
            </article>

            <article className="proof-folder">
              <div className="proof-folder-top">
                <span>04</span>
                <span>RESILIENCE</span>
              </div>

              <h3>Recovery</h3>

              <p>
                Failure scenarios, scaling tests, rollback records, recovery
                output, and service restoration evidence.
              </p>

              <div className="proof-file">
                <span>rollback-test.md</span>
                <span>MD</span>
              </div>

              <div className="proof-file">
                <span>scaling-test.md</span>
                <span>MD</span>
              </div>

              <div className="proof-file">
                <span>recovery-result.txt</span>
                <span>TEXT</span>
              </div>
            </article>
          </div>
        </div>
      </section>

      {/* INTERVIEW VIEW */}
      <section className="section">
        <div className="container">
          <div className="interview-proof">
            <div>
              <div className="section-kicker">Interview View</div>

              <h2 className="section-title">
                Every architecture claim can be connected to evidence.
              </h2>

              <p className="section-description">
                This lets the project move beyond “I used AWS” into concrete
                explanations of what was configured, why it was configured,
                what was tested, and what the actual result was.
              </p>
            </div>

            <div className="interview-chain">
              <div>
                <span>WHY</span>
                <strong>Design decision</strong>
              </div>

              <div>
                <span>HOW</span>
                <strong>Implementation</strong>
              </div>

              <div>
                <span>TEST</span>
                <strong>Validation procedure</strong>
              </div>

              <div>
                <span>PROOF</span>
                <strong>Actual result</strong>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* NAVIGATION */}
      <section className="section">
        <div className="container">
          <div className="security-main">
            <div className="section-kicker">Continue</div>

            <h2 className="section-title">
              Evidence connects the platform together.
            </h2>

            <p className="section-description">
              Move back into security or continue into the documentation
              portal to understand how the platform is operated.
            </p>

            <div className="hero-actions">
              <NavLink to="/security" className="primary-button">
                Security Center
              </NavLink>

              <NavLink to="/docs" className="secondary-button">
                Documentation
              </NavLink>

              <NavLink to="/cicd" className="secondary-button">
                CI/CD
              </NavLink>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Evidence