import { NavLink } from 'react-router-dom'

const services = [
  {
    name: 'Catalog API',
    status: 'Healthy',
    latency: 'Tracked',
    traffic: 'Application metrics',
  },
  {
    name: 'Order API',
    status: 'Healthy',
    latency: 'Tracked',
    traffic: 'Application metrics',
  },
  {
    name: 'Order Worker',
    status: 'Monitored',
    latency: 'Tracked',
    traffic: 'Queue metrics',
  },
  {
    name: 'RDS MySQL',
    status: 'Protected',
    latency: 'Tracked',
    traffic: 'Database metrics',
  },
  {
    name: 'SQS',
    status: 'Monitored',
    latency: 'N/A',
    traffic: 'Queue depth',
  },
  {
    name: 'EKS',
    status: 'Monitored',
    latency: 'Node / Pod',
    traffic: 'Cluster metrics',
  },
]

const logEvents = [
  ['12:41:08', 'Order API', 'INFO', 'Order request accepted'],
  ['12:41:13', 'Catalog API', 'INFO', 'Product lookup completed'],
  ['12:41:19', 'Order Worker', 'INFO', 'Queue message received'],
  ['12:41:27', 'RDS MySQL', 'INFO', 'Database operation recorded'],
  ['12:41:34', 'Security', 'EVENT', 'Security telemetry available'],
]

function Observability() {
  return (
    <div className="observability-page">
      {/* TOP BAR */}
      <section className="section observability-hero">
        <div className="container">
          <div className="obs-topline">
            <div>
              <div className="section-kicker">Observability Center</div>

              <h1 className="obs-title">
                See the system
                <br />
                <span>while it is running.</span>
              </h1>

              <p className="section-description obs-description">
                CloudCart is designed to connect infrastructure metrics,
                application telemetry, logs, traces, and security events into
                one operational view.
              </p>
            </div>

            <div className="obs-live-panel">
              <div className="obs-live-dot" />
              <div>
                <strong>OBSERVABILITY PLANE</strong>
                <span>DESIGNED FOR RUNTIME VISIBILITY</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* METRICS DASHBOARD */}
      <section className="section obs-dashboard-section">
        <div className="container">
          <div className="dashboard-toolbar">
            <div>
              <span className="dashboard-label">PLATFORM SNAPSHOT</span>
              <strong>CloudCart Runtime View</strong>
            </div>

            <span className="dashboard-mode">ENGINEERING VIEW</span>
          </div>

          <div className="obs-metric-grid">
            <div className="obs-metric">
              <span>REQUEST FLOW</span>
              <strong>API → EKS → DATA</strong>
              <small>Application request path</small>
            </div>

            <div className="obs-metric">
              <span>COMPUTE</span>
              <strong>Pods + Nodes</strong>
              <small>Kubernetes workload visibility</small>
            </div>

            <div className="obs-metric">
              <span>DATA</span>
              <strong>RDS + DynamoDB</strong>
              <small>Persistence monitoring</small>
            </div>

            <div className="obs-metric">
              <span>EVENTS</span>
              <strong>SQS + Events</strong>
              <small>Asynchronous workload signals</small>
            </div>
          </div>
        </div>
      </section>

      {/* SERVICE HEALTH MATRIX */}
      <section className="section">
        <div className="container">
          <div className="obs-section-heading">
            <div>
              <div className="section-kicker">Service Health</div>

              <h2 className="section-title">
                One operational view across the stack.
              </h2>
            </div>

            <p className="section-description">
              The final implementation will connect these views to real
              telemetry generated by the deployed CloudCart environment.
            </p>
          </div>

          <div className="health-matrix">
            <div className="health-head">
              <span>SERVICE</span>
              <span>STATE</span>
              <span>TELEMETRY</span>
              <span>SIGNAL</span>
            </div>

            {services.map((service) => (
              <div className="health-row" key={service.name}>
                <strong>{service.name}</strong>

                <span className="health-state">
                  <i />
                  {service.status}
                </span>

                <span>{service.latency}</span>

                <span>{service.traffic}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TELEMETRY TRIAD */}
      <section className="section">
        <div className="container">
          <div className="obs-section-heading">
            <div>
              <div className="section-kicker">Telemetry</div>

              <h2 className="section-title">
                Metrics, logs, and traces tell different parts of the story.
              </h2>
            </div>
          </div>

          <div className="telemetry-triad">
            <article className="telemetry-card telemetry-primary">
              <div className="telemetry-top">
                <span>01</span>
                <span>METRICS</span>
              </div>

              <h3>What is changing?</h3>

              <p>
                Infrastructure and application metrics expose resource usage,
                workload behavior, request patterns, and service-level
                signals.
              </p>

              <div className="telemetry-visual">
                <span style={{ height: '35%' }} />
                <span style={{ height: '52%' }} />
                <span style={{ height: '44%' }} />
                <span style={{ height: '67%' }} />
                <span style={{ height: '59%' }} />
                <span style={{ height: '78%' }} />
                <span style={{ height: '71%' }} />
                <span style={{ height: '88%' }} />
                <span style={{ height: '63%' }} />
                <span style={{ height: '74%' }} />
              </div>
            </article>

            <article className="telemetry-card">
              <div className="telemetry-top">
                <span>02</span>
                <span>LOGS</span>
              </div>

              <h3>What happened?</h3>

              <p>
                Structured application and infrastructure logs provide the
                event-level detail required during troubleshooting.
              </p>

              <div className="log-preview">
                <code>[INFO] catalog request</code>
                <code>[INFO] order accepted</code>
                <code>[EVENT] security signal</code>
              </div>
            </article>

            <article className="telemetry-card">
              <div className="telemetry-top">
                <span>03</span>
                <span>TRACES</span>
              </div>

              <h3>Where did time go?</h3>

              <p>
                Distributed tracing helps connect a single customer request
                across multiple application services.
              </p>

              <div className="trace-preview">
                <div>
                  <span>Gateway</span>
                  <i />
                </div>

                <div>
                  <span>API</span>
                  <i />
                </div>

                <div>
                  <span>Worker</span>
                  <i />
                </div>

                <div>
                  <span>Database</span>
                  <i />
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>

      {/* OPERATIONS TIMELINE */}
      <section className="section">
        <div className="container">
          <div className="ops-panel">
            <div className="ops-panel-head">
              <div>
                <div className="section-kicker">Operations Timeline</div>
                <h2>Recent platform signals</h2>
              </div>

              <span>EXAMPLE EVENT VIEW</span>
            </div>

            <div className="event-log">
              {logEvents.map(([time, source, level, message]) => (
                <div className="event-log-row" key={`${time}-${source}`}>
                  <time>{time}</time>
                  <strong>{source}</strong>
                  <span className={`event-level ${level.toLowerCase()}`}>
                    {level}
                  </span>
                  <p>{message}</p>
                </div>
              ))}
            </div>

            <div className="event-note">
              These entries are interface examples only and are not presented
              as live production telemetry.
            </div>
          </div>
        </div>
      </section>

      {/* OBSERVABILITY STACK */}
      <section className="section">
        <div className="container">
          <div className="obs-section-heading">
            <div>
              <div className="section-kicker">Observability Stack</div>

              <h2 className="section-title">
                Visibility should follow the architecture.
              </h2>
            </div>
          </div>

          <div className="observability-stack">
            <div className="stack-layer">
              <span>APPLICATION</span>

              <div>
                <strong>Node.js APIs</strong>
                <small>Logs · Metrics · Traces</small>
              </div>
            </div>

            <div className="stack-layer">
              <span>KUBERNETES</span>

              <div>
                <strong>EKS Workloads</strong>
                <small>Pods · Nodes · Containers</small>
              </div>
            </div>

            <div className="stack-layer">
              <span>AWS</span>

              <div>
                <strong>CloudWatch</strong>
                <small>Infrastructure · Alarms · Dashboards</small>
              </div>
            </div>

            <div className="stack-layer">
              <span>AUDIT</span>

              <div>
                <strong>CloudTrail</strong>
                <small>AWS API activity</small>
              </div>
            </div>

            <div className="stack-layer">
              <span>SECURITY</span>

              <div>
                <strong>GuardDuty + Security Hub</strong>
                <small>Findings · Events · Response</small>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAILURE INVESTIGATION */}
      <section className="section">
        <div className="container">
          <div className="investigation-grid">
            <div>
              <div className="section-kicker">Troubleshooting Workflow</div>

              <h2 className="section-title">
                From symptom to root cause.
              </h2>

              <p className="section-description">
                Observability should help an engineer move from an alert to
                evidence instead of guessing where the problem originated.
              </p>
            </div>

            <div className="investigation-chain">
              <div>
                <span>01</span>
                <strong>Alert</strong>
                <small>A signal indicates abnormal behavior.</small>
              </div>

              <div>
                <span>02</span>
                <strong>Metrics</strong>
                <small>Determine scope and timing.</small>
              </div>

              <div>
                <span>03</span>
                <strong>Logs</strong>
                <small>Find the event-level context.</small>
              </div>

              <div>
                <span>04</span>
                <strong>Trace</strong>
                <small>Follow the request path.</small>
              </div>

              <div>
                <span>05</span>
                <strong>Evidence</strong>
                <small>Document what actually happened.</small>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* NAVIGATION */}
      <section className="section">
        <div className="container">
          <div className="security-main">
            <div className="section-kicker">Continue</div>

            <h2 className="section-title">
              Visibility connects directly to evidence and security.
            </h2>

            <p className="section-description">
              Continue to the Evidence Center to see how CloudCart will
              document real validation results from the deployed platform.
            </p>

            <div className="hero-actions">
              <NavLink to="/evidence" className="primary-button">
                Evidence Center
              </NavLink>

              <NavLink to="/security" className="secondary-button">
                Security Center
              </NavLink>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Observability